# Check for broken links
name: Link-check
on:
  push:
    paths:
      - "docs/**"
    branches:
      - main
  pull_request:
    paths: "docs/**"
jobs:
  lint_docs:
    name: Broken Links
    runs-on:
      group: databricks-eng-protected-runner-group
      labels: linux-ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: ".markdownlinkcheck.json"
