name: Lint
on: [ pull_request ]

jobs:
  golangci:
    name: lint
    runs-on:
      group: databricks-eng-protected-runner-group
      labels: linux-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.50.1
